### ISSUE TITLE
CSS-Purge didn't do anything to my test file

### ISSUE THREAD

**Issue by bartkusa** [rbtech/css-purge#3]
I couldn't find any examples of what CSS-Purge does, so I don't know what to expect from it. I tried it out with this input file:

``` css
.test {
    color: red;
    color: blue;
    font-weight: bold;
}
.test2 {
    color: green;
}
.test2 {
    color: green;
    color: green;
}
.test {
    color: purple;
}
.invalidProperties {
    invalid:property;
}
```

I expected the output to be:

``` css
.test {
    font-weight: bold;
}
.test2 {
    color: green;
}
.test {
    color: purple;
}
.invalidProperties {
    invalid:property;
}
```

Instead, this is what CSS-Purge actually output:

``` css
.test {
    color: red;
    color: blue;
    font-weight: bold;
}
.test2 {
    color: green;
}
.test2 {
    color: green;
    color: green;
}
.test {
    color: purple;
}
.invalidProperties {
    invalid: property;
}
```

What should I have expected? What kinds of redundancies and duplicates is CSS-Purge supposed to find?
