### ISSUE TITLE
Unsafe transforms

### ISSUE THREAD

**Issue by brandonkal** [rbtech/css-purge#35]
I have noticed this tool makes some unsafe transforms:
Input CSS:
```
.entry-title {
  line-height: 1.3;
  color: #222;
}

.entry-title a {
  color: #222;
}

.entry-title a:hover {
  color: #666;
}
```

Output CSS:
```
.entry-title {
  line-height: 1.3;
  color: #666;
}

.entry-title a {
  color: #222;
}
```

Here is another simple example:
Input:
```
small {
  font-size: 80%
}
small {
  font-size: 85%
}
```
Output:
```
small {
  font-size: 80%
}
```

**Comment by AndrewEQ** [comment]
Thanks for the feedback, will look into it asap.

**Comment by AndrewEQ** [comment]
Hey @brandonkal, 

I think you may have an older version; I just tested the CSS:

```css
.entry-title {
  line-height: 1.3;
  color: #222;
}

.entry-title a {
  color: #222;
}

.entry-title a:hover {
  color: #666;
}

small {
  font-size: 80%
}
small {
  font-size: 85%
}
```

and my output was this:
```css
.entry-title {
  line-height: 1.3;
  color: #222;
}

.entry-title a {
  color: #222;
}

.entry-title a:hover {
  color: #666;
}

small {
  font-size: 85%;
}
```
