### ISSUE TITLE
After purge, all the hover styles are removed.

### ISSUE THREAD

**Issue by metalbrick** [rbtech/css-purge#55]
```css
.toppest-right .iconfont {
  font-size: 1.4rem;
}
.toppest-right a:hover {
  text-decoration: none;
  color: #23a4db;
}
#topHeader {
  background: #08a1e5 url("../img/top-header.jpg") top no-repeat;
}
```
After css-purge

```css
.toppest-right,
.toppest-right a {
  color: #0170a0;
}
.toppest-right .iconfont {
  font-size: 1.4rem;
}
#topHeader {
  background: #08a1e5 url("../img/top-header.jpg") top no-repeat;
}
```
