### ISSUE TITLE
Is there a way to purge media queries of duplicated rules?

### ISSUE THREAD

**Issue by Carl-Hugo** [rbtech/css-purge#60]
Hi, I'd like to purge duplicated rules from inside media queries, but based on #14 this does not seem possible. 

Here is what I want to do:

Input:

```css
.panel {
    padding: 10px;
    background-color: blue;
}

@media (prefers-color-scheme: dark) {
    .panel {
        padding: 10px;
        background-color: red;
    }
}
```
Expected output:
```css
.panel {
    padding: 10px;
    background-color: blue;
}
@media (prefers-color-scheme: dark) {
    .panel {
        background-color: red;
    }
}
```

Is this possible using css-purge or do you know of a way I could achieve that result?
Thanks
