### ISSUE TITLE
Invalid CSS Syntax after purge

### ISSUE THREAD

**Issue by Irtiza90** [rbtech/css-purge#72]
Here i give input, which is valid CSS
```css
h6 {
  font-family: niveau-grotesk-medium, sans-serif !important;
}
```
after purging it is converted to this, which is invalid
```css
h6 {
  font-family: niveau-grotesk-medium, "sans-serif!important";
}
```
i tried changing the input to this to prevent the error, and apparently that's invalid
```css
font-family: niveau-grotesk-medium, "sans-serif" !important;
```
